baseURL = "https://lucasss1916.github.io"
languageCode = "en-us"
title = "Lucas`s blog"
theme = "github-style"

[params]
  author = "Lucas"
  avatar = "/images/logo.PNG"
  github = "https://github.com/Lucasss1916"


