[module]
  [[module.imports]]
    path = "github.com/g1eny0ung/hugo-theme-dream"
    
baseURL = 'https://lucasss1916.github.io'
languageCode = 'en-us'
title = 'Lucas`s blog'
theme = "dream"

[params]
avatar = "images/logo.PNG"
logoWidth = "120px"
logoHeight = "40px"
logoLink = "/"

# 主题配色
lightTheme = "emerald"
darkTheme = "forest"
author = "Lucas"
headerTitle = "Lucas`s Blog"
