baseURL = "https://lucasss1916.github.io"
languageCode = "en-us"
title = "Lucas`s blog"
theme = "github-style"

[params]
  author = "Lucas"
  avatar = "/images/avatar.jpg"
  headerIcon = "/images/avatar.jpg"
  github = "Lucasss1916"
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  favicon = "/icon.ico"

